import React, { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const translations = {
  en: {
    home: "Home",
    about: "About",
    bookFlight: "Book Flight",
    myReservations: "My Reservations",
    login: "Login",
    logout: "Logout",
    search: "AI Search",
    brand: "AirGo",
    // Home Page
    stopover: "Stopover",
    hotels: "Hotels",
    cars: "Cars",
    book: "Book",
    manage: "Manage",
    checkIn: "Check-in",
    flightStatus: "Flight status",
    flightSchedule: "Flight schedule",
    roundTrip: "Round trip",
    oneWay: "One way",
    multiCity: "Multi-city",
    bookWithMiles: "Book with Miles",
    from: "From",
    to: "To",
    departure: "Departure",
    return: "Return",
    passengersClass: "Passengers & Class",
    searchFlights: "Search Flights",
    recentSearches: "Recent searches",
    manageBooking: "Manage my booking",
    manageDesc: "Modify your upcoming trip, add baggage, or choose your seat.",
    bookingRef: "Booking Reference / E-ticket",
    lastName: "Last Name",
    findBooking: "Find Booking",
    selectDest: "Select destination",
    retrieveBooking: "Retrieve Booking",
    tellMeMoreManage: "Tell me more about managing my booking",
    onlineCheckIn: "Online Check-in",
    checkInDesc:
      "Check in online 48 hours before your flight to save time at the airport.",
    bookingRefTicket: "Booking Reference / Ticket No.",
    checkInNow: "Check-in Now",
    lookingFor: "Looking for",
    flightTrackingUpdate:
      "We are currently updating our real-time flight tracking systems to provide you with the most accurate information.",
    travelRequirements:
      "Read more about the latest travel requirements for your next destination",
    learnMore: "Learn more",
    // Auth
    welcomeBack: "Welcome back",
    signInToAccount: "Sign in to your AirGo account",
    username: "Username",
    password: "Password",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    signIn: "Sign In",
    signingIn: "Signing In...",
    noAccount: "Don't have an account?",
    signUpNow: "Sign up now!",
    createAccount: "Create your account",
    signUpForAirGo: "Sign up for AirGo",
    email: "Email",
    confirmPassword: "Confirm Password",
    firstName: "First Name",
    ssn: "SSN",
    dob: "Date of Birth",
    gender: "Gender",
    selectGender: "Select Gender",
    male: "Male",
    female: "Female",
    city: "City",
    state: "State",
    phoneNumber: "Phone Number",
    register: "Register",
    // Plan
    travelSupport: "TRAVEL SUPPORT",
    planConfidence: "Plan your travel with confidence",
    planDesc:
      "Find help with your bookings and travel plans, and see what to expect along your journey.",
    reqDubai: "Travel Requirements for Dubai",
    reqDubaiDesc:
      "Stay informed and prepared for your trip to Dubai with essential travel requirements.",
    insurance: "Multi-risk travel insurance",
    insuranceDesc:
      "Comprehensive protection for your peace of mind, covering a range of potential travel risks.",
    reqDest: "Travel Requirements by destinations",
    reqDestDesc:
      "Stay informed and plan your trip with ease, as we provide up-to-date information.",
    // Memories
    makeMemories: "Travel to Make Memories",
    bookRelax: "Book & Relax",
    bookRelaxDesc:
      "Sit back, unwind, and enjoy the journey while we take care of everything else.",
    smartChecklist: "Smart Checklist",
    smartChecklistDesc:
      "Introducing Smart Checklist, the innovative solution revolutionizing your travel.",
    saveMore: "Save More",
    saveMoreDesc:
      "From discounted ticket prices to exclusive deals, we prioritize affordability.",
    // Lounge
    lounge: "Lounge",
    minorLounge: "Unaccompanied Minor Lounge",
    tranq: "Experience Tranquility",
    tranqDesc: "Serenity Haven offers a tranquil escape.",
    elevate: "Elevate Your Experience",
    elevateDesc: "Designed for discerning travelers.",
    welcoming: "A Welcoming Space",
    welcomingDesc: "Creating a family-friendly atmosphere.",
    culinary: "A Culinary Delight",
    culinaryDesc: "Immerse yourself in a world of flavors.",
    // Footer
    subscribe: "Subscribe",
    contact: "Contact",
    information: "Information",
    footerDesc:
      "Where Excellence Takes Flight. Join us for an unforgettable journey.",
    supportCenter: "Support Center",
    // Booking Flow
    selectFlight: "Select Your Flight",
    viewFares: "View Fares",
    hideFares: "Hide Fares",
    selectFare: "Select Fare",
    stops: "Stops",
    direct: "Direct",
    perPerson: "per person",
    // Classes & Features
    Economy: "Economy",
    Business: "Business",
    FirstClass: "First Class",
    light: "Light",
    flex: "Flex",
    bag23kg: "1x 23kg Bag",
    bag2x23kg: "2x 23kg Bags",
    refundable: "Refundable",
    nonRefundable: "Non-Refundable",
    standardSeat: "Standard Seat",
    frontSeat: "Front Seat Selection",
    // Reservation Page
    completeBooking: "Complete Your Booking",
    fillDetails: "Fill in the details below to secure your seat.",
    passengerDetails: "Passenger Details",
    flightSelection: "Flight Selection",
    chooseFlight: "Choose Flight",
    travelClass: "Travel Class",
    selectSeat: "Select Your Seat",
    enhanceTrip: "Enhance Your Trip",
    addHotel: "Add a Hotel",
    rentCar: "Rent a Car",
    save20: "Save up to 20%",
    from30: "From $30/day",
    noSeats: "No seats available for this flight.",
    selectFlightToView: "Please select a flight to view the seat map.",
    // Dynamic Cities
    city_New_York: "New York",
    city_London: "London",
    city_Dubai: "Dubai",
    city_Riyadh: "Riyadh",
    city_Paris: "Paris",
    city_Jeddah: "Jeddah",
    city_Cairo: "Cairo",
    city_Tokyo: "Tokyo",
    city_Singapore: "Singapore",
    city_Istanbul: "Istanbul",
    // Seat Map
    front: "Front",
    wing: "Wing",
    rear: "Rear",
    exit: "EXIT",
    available: "Available",
    selected: "Selected",
    booked: "Booked",
    // Passengers List
    passengersList: "Passengers List",
    noPassengers: "No passengers found.",
    // Summary & Payment
    tripSummary: "Trip Summary",
    flight: "Flight",
    route: "Route",
    class: "Class",
    seat: "Seat",
    notSelected: "Not Selected",
    totalPrice: "Total Price",
    continuePayment: "Continue to Payment",
    processing: "Processing...",
    securePayment: "Secure Payment",
    verifiedFlight: "Verified Flight",
    support247: "24/7 Support",
  },
  ar: {
    home: "الرئيسية",
    about: "عن الشركة",
    bookFlight: "حجز طيران",
    myReservations: "حجوزاتي",
    login: "تسجيل دخول",
    logout: "تسجيل خروج",
    search: "بحث ذكي",
    brand: "أير جو",
    // Home Page
    stopover: "توقف",
    hotels: "فنادق",
    cars: "سيارات",
    book: "حجز",
    manage: "إدارة الحجز",
    checkIn: "إتمام السفر",
    flightStatus: "حالة الرحلة",
    flightSchedule: "جدول الرحلات",
    roundTrip: "ذهاب وعودة",
    oneWay: "ذهاب فقط",
    multiCity: "وجهات متعددة",
    bookWithMiles: "الحجز بالأميال",
    from: "من",
    to: "إلى",
    departure: "المغادرة",
    return: "العودة",
    passengersClass: "الركاب والدرجة",
    searchFlights: "بحث عن رحلات",
    recentSearches: "عمليات البحث الأخيرة",
    manageBooking: "إدارة حجزي",
    manageDesc: "تعديل رحلتك القادمة، إضافة أمتعة، أو اختيار مقعدك.",
    bookingRef: "مرجع الحجز / التذكرة الإلكترونية",
    lastName: "اسم العائلة",
    findBooking: "البحث عن حجز",
    selectDest: "اختر الوجهة",
    retrieveBooking: "استرجاع الحجز",
    tellMeMoreManage: "أخبرني المزيد عن إدارة حجزي",
    onlineCheckIn: "إتمام إجراءات السفر عبر الإنترنت",
    checkInDesc:
      "سجل وصولك عبر الإنترنت قبل 48 ساعة من رحلتك لتوفير الوقت في المطار.",
    bookingRefTicket: "مرجع الحجز / رقم التذكرة",
    checkInNow: "سجل الآن",
    lookingFor: "تبحث عن",
    flightTrackingUpdate:
      "نقوم حاليًا بتحديث أنظمة تتبع الرحلات المباشرة لتقديم أدق المعلومات لك.",
    travelRequirements: "اقرأ المزيد عن أحدث متطلبات السفر لوجهتك القادمة",
    learnMore: "اعرف المزيد",
    // Auth
    welcomeBack: "مرحبًا بعودتك",
    signInToAccount: "سجل الدخول إلى حسابك في أير جو",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    rememberMe: "تذكرني",
    forgotPassword: "نسيت كلمة المرور؟",
    signIn: "دخول",
    signingIn: "جاري الدخول...",
    noAccount: "ليس لديك حساب؟",
    signUpNow: "سجل الآن!",
    createAccount: "أنشئ حسابك",
    signUpForAirGo: "سجل في أير جو",
    email: "البريد الإلكتروني",
    confirmPassword: "تأكيد كلمة المرور",
    firstName: "الاسم الأول",
    ssn: "رقم الهوية",
    dob: "تاريخ الميلاد",
    gender: "الجنس",
    selectGender: "اختر الجنس",
    male: "ذكر",
    female: "أنثى",
    city: "المدينة",
    state: "المنطقة",
    phoneNumber: "رقم الهاتف",
    register: "تسجيل",
    // Plan
    travelSupport: "دعم السفر",
    planConfidence: "خطط لرحلتك بثقة",
    planDesc:
      "احصل على المساعدة في حجوزاتك وخطط سفرك، واكتشف ما ينتظرك خلال رحلتك.",
    reqDubai: "متطلبات السفر إلى دبي",
    reqDubaiDesc:
      "ابق على اطلاع واستعد لرحلتك إلى دبي مع متطلبات السفر الأساسية.",
    insurance: "تأمين سفر متعدد المخاطر",
    insuranceDesc:
      "حماية شاملة لراحة بالك، تغطي مجموعة من مخاطر السفر المحتملة.",
    reqDest: "متطلبات السفر حسب الوجهة",
    reqDestDesc:
      "ابق على اطلاع وخطط لرحلتك بسهولة، حيث نقدم لك أحدث المعلومات.",
    // Memories
    makeMemories: "سافر لتصنع ذكريات",
    bookRelax: "احجز واسترخ",
    bookRelaxDesc: "استرخ واستمتع بالرحلة بينما نهتم نحن بكل شيء آخر.",
    smartChecklist: "قائمة التحقق الذكية",
    smartChecklistDesc:
      "نقدم لك قائمة التحقق الذكية، الحل المبتكر الذي يحدث ثورة في سفرك.",
    saveMore: "وفر أكثر",
    saveMoreDesc:
      "من أسعار التذاكر المخفضة إلى العروض الحصرية، نضع القدرة على تحمل التكاليف في أولوياتنا.",
    // Lounge
    lounge: "الصالة",
    minorLounge: "صالة القاصرين غير المصحوبين",
    tranq: "جرب الهدوء",
    tranqDesc: "ملاذ الصفاء يقدم هروباً هادئاً.",
    elevate: "ارتقِ بتجربتك",
    elevateDesc: "صممت للمسافرين المميزين.",
    welcoming: "مساحة ترحيبية",
    welcomingDesc: "خلق جو مناسب للعائلة.",
    culinary: "متعة الطهي",
    culinaryDesc: "اغمر نفسك في عالم من النكهات.",
    // Footer
    subscribe: "اشترك",
    contact: "اتصل بنا",
    information: "معلومات",
    footerDesc: "حيث يأخذ التميز مجراه. انضم إلينا في رحلة لا تُنسى.",
    supportCenter: "مركز الدعم",
    // Booking Flow
    selectFlight: "اختر رحلتك",
    viewFares: "عرض الأسعار",
    hideFares: "إخفاء الأسعار",
    selectFare: "اختر السعر",
    stops: "توقفات",
    direct: "مباشر",
    perPerson: "للشخص",
    // Classes & Features
    Economy: "سياحية",
    Business: "أعمال",
    FirstClass: "أولى",
    light: "لايت",
    flex: "فليكس",
    bag23kg: "1x 23كجم حقيبة",
    bag2x23kg: "2x 23كجم حقائب",
    refundable: "قابل للاسترداد",
    nonRefundable: "غير قابل للاسترداد",
    standardSeat: "مقعد قياسي",
    frontSeat: "اختيار مقعد أمامي",
    // Reservation Page
    completeBooking: "أكمل حجزك",
    fillDetails: "املأ التفاصيل أدناه لتأمين مقعدك.",
    passengerDetails: "تفاصيل الركاب",
    flightSelection: "اختيار الرحلة",
    chooseFlight: "اختر الرحلة",
    travelClass: "درجة السفر",
    selectSeat: "اختر مقعدك",
    enhanceTrip: "عزز رحلتك",
    addHotel: "أضف فندقًا",
    rentCar: "استأجر سيارة",
    save20: "وفر حتى 20%",
    from30: "من $30/يوم",
    noSeats: "لا توجد مقاعد متاحة لهذه الرحلة.",
    selectFlightToView: "يرجى اختيار رحلة لعرض خريطة المقاعد.",
    // Dynamic Cities
    city_New_York: "نيويورك",
    city_London: "لندن",
    city_Dubai: "دبي",
    city_Riyadh: "الرياض",
    city_Paris: "باريس",
    city_Jeddah: "جدة",
    city_Cairo: "القاهرة",
    city_Tokyo: "طوكيو",
    city_Singapore: "سنغافورة",
    city_Istanbul: "إسطنبول",
    // Seat Map
    front: "أمام",
    wing: "جناح",
    rear: "خلف",
    exit: "مخرج",
    available: "متاح",
    selected: "محدد",
    booked: "محجوز",
    // Passengers List
    passengersList: "قائمة الركاب",
    noPassengers: "لم يتم العثور على ركاب.",
    // Summary & Payment
    tripSummary: "ملخص الرحلة",
    flight: "الرحلة",
    route: "المسار",
    class: "الدرجة",
    seat: "المقعد",
    notSelected: "غير محدد",
    totalPrice: "الإجمالي",
    continuePayment: "المتابعة للدفع",
    processing: "جاري المعالجة...",
    securePayment: "دفع آمن",
    verifiedFlight: "رحلة مؤكدة",
    support247: "دعم 24/7",
  },
  fr: {
    home: "Accueil",
    about: "À propos",
    bookFlight: "Réserver",
    myReservations: "Mes Réservations",
    login: "Connexion",
    logout: "Déconnexion",
    search: "Recherche IA",
    brand: "AirGo",
    // Home Page
    stopover: "Escale",
    hotels: "Hôtels",
    cars: "Voitures",
    book: "Réserver",
    manage: "Gérer",
    checkIn: "Enregistrement",
    flightStatus: "Statut du vol",
    flightSchedule: "Horaires",
    roundTrip: "Aller-retour",
    oneWay: "Aller simple",
    multiCity: "Multi-destinations",
    bookWithMiles: "Réserver avec des Miles",
    from: "De",
    to: "À",
    departure: "Départ",
    return: "Retour",
    passengersClass: "Passagers et Classe",
    searchFlights: "Rechercher",
    recentSearches: "Recherches récentes",
    manageBooking: "Gérer ma réservation",
    manageDesc:
      "Modifiez votre voyage, ajoutez des bagages ou choisissez votre siège.",
    bookingRef: "Référence de réservation",
    lastName: "Nom de famille",
    findBooking: "Trouver ma réservation",
    selectDest: "Choisir la destination",
    retrieveBooking: "Retrouver ma réservation",
    tellMeMoreManage: "En savoir plus sur la gestion de ma réservation",
    onlineCheckIn: "Enregistrement en ligne",
    checkInDesc:
      "Enregistrez-vous en ligne 48 heures avant votre vol pour gagner du temps à l'aéroport.",
    bookingRefTicket: "Référence de réservation / N° de billet",
    checkInNow: "S'enregistrer maintenant",
    lookingFor: "Vous cherchez",
    flightTrackingUpdate:
      "Nous mettons actuellement à jour nos systèmes de suivi des vols.",
    travelRequirements: "En savoir plus sur les dernières exigences de voyage",
    learnMore: "En savoir plus",
    // Auth
    welcomeBack: "Bon retour",
    signInToAccount: "Connectez-vous à votre compte AirGo",
    username: "Nom d'utilisateur",
    password: "Mot de passe",
    rememberMe: "Se souvenir de moi",
    forgotPassword: "Mot de passe oublié ?",
    signIn: "Se connecter",
    signingIn: "Connexion...",
    noAccount: "Pas de compte ?",
    signUpNow: "Inscrivez-vous !",
    createAccount: "Créer votre compte",
    signUpForAirGo: "Inscrivez-vous à AirGo",
    email: "Email",
    confirmPassword: "Confirmer le mot de passe",
    firstName: "Prénom",
    ssn: "Sécurité sociale",
    dob: "Date de naissance",
    gender: "Sexe",
    selectGender: "Sélectionner le sexe",
    male: "Homme",
    female: "Femme",
    city: "Ville",
    state: "État",
    phoneNumber: "Numéro de téléphone",
    register: "S'inscrire",
    // Plan
    travelSupport: "ASSISTANCE VOYAGE",
    planConfidence: "Planifiez votre voyage en toute confiance",
    planDesc:
      "Trouvez de l'aide pour vos réservations et vos projets de voyage, et découvrez ce qui vous attend tout au long de votre périple.",
    reqDubai: "Conditions de voyage pour Dubaï",
    reqDubaiDesc:
      "Restez informé et préparez votre voyage à Dubaï avec les conditions de voyage essentielles.",
    insurance: "Assurance voyage multirisque",
    insuranceDesc:
      "Une protection complète pour votre tranquillité d'esprit, couvrant un éventail de risques potentiels liés au voyage.",
    reqDest: "Conditions de voyage par destination",
    reqDestDesc:
      "Restez informé et planifiez votre voyage en toute simplicité, car nous fournissons des informations à jour.",
    // Memories
    makeMemories: "Voyagez pour créer des souvenirs",
    bookRelax: "Réservez et détendez-vous",
    bookRelaxDesc:
      "Asseyez-vous, détendez-vous et profitez du voyage pendant que nous nous occupons de tout le reste.",
    smartChecklist: "Liste de contrôle intelligente",
    smartChecklistDesc:
      "Découvrez la Smart Checklist, la solution innovante qui révolutionne votre voyage.",
    saveMore: "Économisez plus",
    saveMoreDesc:
      "Des prix de billets réduits aux offres exclusives, nous privilégions l'accessibilité.",
    // Lounge
    lounge: "Salon",
    minorLounge: "Salon pour mineurs non accompagnés",
    tranq: "Découvrez la tranquillité",
    tranqDesc: "Serenity Haven offre une évasion tranquille.",
    elevate: "Élevez votre expérience",
    elevateDesc: "Conçu pour les voyageurs exigeants.",
    welcoming: "Un espace accueillant",
    welcomingDesc: "Créer une atmosphère familiale.",
    culinary: "Un délice culinaire",
    culinaryDesc: "Plongez dans un monde de saveurs.",
    // Footer
    subscribe: "S'abonner",
    contact: "Contact",
    information: "Informations",
    footerDesc:
      "Où l'excellence prend son envol. Rejoignez-nous pour un voyage inoubliable.",
    supportCenter: "Centre d'aide",
    // Booking Flow
    selectFlight: "Sélectionnez votre vol",
    viewFares: "Voir les tarifs",
    hideFares: "Masquer les tarifs",
    selectFare: "Choisir ce tarif",
    stops: "Escales",
    direct: "Direct",
    perPerson: "par personne",
    // Classes & Features
    Economy: "Économique",
    Business: "Affaires",
    FirstClass: "Première",
    light: "Light",
    flex: "Flex",
    bag23kg: "1x 23kg Bagage",
    bag2x23kg: "2x 23kg Bagages",
    refundable: "Remboursable",
    nonRefundable: "Non remboursable",
    standardSeat: "Siège standard",
    frontSeat: "Siège avant",
    // Reservation Page
    completeBooking: "Finalisez votre réservation",
    fillDetails: "Remplissez les détails ci-dessous pour réserver votre siège.",
    passengerDetails: "Détails du passager",
    flightSelection: "Sélection du vol",
    chooseFlight: "Choisir un vol",
    travelClass: "Classe de voyage",
    selectSeat: "Sélectionnez votre siège",
    enhanceTrip: "Améliorez votre voyage",
    addHotel: "Ajouter un hôtel",
    rentCar: "Louer une voiture",
    save20: "Économisez jusqu'à 20%",
    from30: "À partir de 30 $/jour",
    noSeats: "Aucun siège disponible pour ce vol.",
    selectFlightToView:
      "Veuillez sélectionner un vol pour voir le plan des sièges.",
    // Dynamic Cities
    city_New_York: "New York",
    city_London: "Londres",
    city_Dubai: "Dubaï",
    city_Riyadh: "Riyad",
    city_Paris: "Paris",
    city_Jeddah: "Djeddah",
    city_Cairo: "Le Caire",
    city_Tokyo: "Tokyo",
    city_Singapore: "Singapour",
    city_Istanbul: "Istanbul",
    // Seat Map
    front: "Avant",
    wing: "Aile",
    rear: "Arrière",
    exit: "SORTIE",
    available: "Disponible",
    selected: "Sélectionné",
    booked: "Réservé",
    // Passengers List
    passengersList: "Liste des passagers",
    noPassengers: "Aucun passager trouvé.",
    // Summary & Payment
    tripSummary: "Résumé du voyage",
    flight: "Vol",
    route: "Itinéraire",
    class: "Classe",
    seat: "Siège",
    notSelected: "Non sélectionné",
    totalPrice: "Prix total",
    continuePayment: "Continuer vers le paiement",
    processing: "Traitement...",
    securePayment: "Paiement sécurisé",
    verifiedFlight: "Vol vérifié",
    support247: "Support 24/7",
  },
  hi: {
    home: "घर",
    about: "के बारे में",
    bookFlight: "फ्लाइट बुक करें",
    myReservations: "मेरी बुकिंग",
    login: "लॉग इन",
    logout: "लॉग आउट",
    search: "AI खोज",
    brand: "एयर गो",
    // Home Page
    stopover: "स्टॉपओवर",
    hotels: "होटल",
    cars: "गाड़ियाँ",
    book: "बुक करें",
    manage: "प्रबंधन करें",
    checkIn: "चेक-इन",
    flightStatus: "उड़ान की स्थिति",
    flightSchedule: "उड़ान अनुसूची",
    roundTrip: "राउंड ट्रिप",
    oneWay: "एक तरफ",
    multiCity: "बहु-शहर",
    bookWithMiles: "माइल्स के साथ बुक करें",
    from: "से",
    to: "को",
    departure: "प्रस्थान",
    return: "वापसी",
    passengersClass: "यात्री और श्रेणी",
    searchFlights: "उड़ानें खोजें",
    recentSearches: "हाल ही की खोजें",
    manageBooking: "मेरी बुकिंग प्रबंधित करें",
    manageDesc:
      "अपनी आगामी यात्रा को संशोधित करें, सामान जोड़ें, या अपनी सीट चुनें।",
    bookingRef: "बुकिंग संदर्भ / ई-टिकट",
    lastName: "उपनाम",
    findBooking: "बुकिंग खोजें",
    selectDest: "गंतव्य चुनें",
    retrieveBooking: "बुकिंग पुनः प्राप्त करें",
    tellMeMoreManage: "मेरी बुकिंग प्रबंधित करने के बारे में और बताएं",
    onlineCheckIn: "ऑनलाइन चेक-इन",
    checkInDesc:
      "हवाई अड्डे पर समय बचाने के लिए अपनी उड़ान से 48 घंटे पहले ऑनलाइन चेक-इन करें।",
    bookingRefTicket: "बुकिंग संदर्भ / टिकट नंबर",
    checkInNow: "अभी चेक-इन करें",
    lookingFor: "क्या आप खोज रहे हैं",
    flightTrackingUpdate:
      "हम वर्तमान में अपने रीयल-टाइम उड़ान ट्रैकिंग सिस्टम को अपडेट कर रहे हैं।",
    travelRequirements:
      "अपने अगले गंतव्य के लिए नवीनतम यात्रा आवश्यकताओं के बारे में और पढ़ें",
    learnMore: "और जानें",
    // Auth
    welcomeBack: "वापसी पर स्वागत है",
    signInToAccount: "अपने एयर गो खाते में साइन इन करें",
    username: "उपयोगकर्ता नाम",
    password: "पासवर्ड",
    rememberMe: "मुझे याद रखें",
    forgotPassword: "पासवर्ड भूल गए?",
    signIn: "साइन इन करें",
    signingIn: "साइन इन हो रहा है...",
    noAccount: "खाता नहीं है?",
    signUpNow: "अभी साइन अप करें!",
    createAccount: "अपना खाता बनाएं",
    signUpForAirGo: "एयर गो के लिए साइन अप करें",
    email: "ईमेल",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    firstName: "प्रथम नाम",
    ssn: "एसएसएन",
    dob: "जन्म तिथि",
    gender: "लिंग",
    selectGender: "लिंग चुनें",
    male: "पुरुष",
    female: "महिला",
    city: "शहर",
    state: "राज्य",
    phoneNumber: "फ़ोन नंबर",
    register: "पंजीकरण करें",
    // Plan
    travelSupport: "यात्रा सहायता",
    planConfidence: "विश्वास के साथ अपनी यात्रा की योजना बनाएं",
    planDesc:
      "अपनी बुकिंग और यात्रा योजनाओं में मदद पाएं, और देखें कि अपनी यात्रा के दौरान क्या उम्मीद करें।",
    reqDubai: "दुबई के लिए यात्रा आवश्यकताएँ",
    reqDubaiDesc:
      "आवश्यक यात्रा आवश्यकताओं के साथ दुबई की अपनी यात्रा के लिए सूचित और तैयार रहें।",
    insurance: "बहु-जोखिम यात्रा बीमा",
    insuranceDesc:
      "आपकी मानसिक शांति के लिए व्यापक सुरक्षा, संभावित यात्रा जोखिमों की एक श्रृंखला को कवर करती है।",
    reqDest: "गंतव्य के अनुसार यात्रा आवश्यकताएँ",
    reqDestDesc:
      "सूचित रहें और आसानी से अपनी यात्रा की योजना बनाएं, क्योंकि हम अद्यतित जानकारी प्रदान करते हैं।",
    // Memories
    makeMemories: "यादें बनाने के लिए यात्रा करें",
    bookRelax: "बुक करें और आराम करें",
    bookRelaxDesc:
      "आराम से बैठें, और यात्रा का आनंद लें जबकि हम बाकी सब चीजों का ध्यान रखते हैं।",
    smartChecklist: "स्मार्ट चेकलिस्ट",
    smartChecklistDesc:
      "पेश है स्मार्ट चेकलिस्ट, आपकी यात्रा में क्रांति लाने वाला अभिनव समाधान।",
    saveMore: "और बचाएं",
    saveMoreDesc:
      "रियायती टिकट की कीमतों से लेकर विशेष सौदों तक, हम सामर्थ्य को प्राथमिकता देते हैं।",
    // Lounge
    lounge: "लाउंज",
    minorLounge: "बेसहारा नाबालिग लाउंज",
    tranq: "शांति का अनुभव करें",
    tranqDesc: "सेरेनिटी हेवन एक शांत पलायन प्रदान करता है।",
    elevate: "अपने अनुभव को ऊपर उठाएं",
    elevateDesc: "समझदार यात्रियों के लिए डिज़ाइन किया गया।",
    welcoming: "एक स्वागत योग्य स्थान",
    welcomingDesc: "एक परिवार के अनुकूल माहौल बनाना।",
    culinary: "एक पाक आनंद",
    culinaryDesc: "स्वाद की दुनिया में डूब जाएं।",
    // Footer
    subscribe: "सदस्यता लें",
    contact: "संपर्क",
    information: "जानकारी",
    footerDesc:
      "जहां उत्कृष्टता उड़ान भरती है। एक अविस्मरणीय यात्रा के लिए हमसे जुड़ें।",
    supportCenter: "सहायता केंद्र",
    // Booking Flow
    selectFlight: "अपनी उड़ान चुनें",
    viewFares: "किराया देखें",
    hideFares: "किराया छुपाएं",
    selectFare: "किराया चुनें",
    stops: "स्टॉप",
    direct: "सीधा",
    perPerson: "प्रति व्यक्ति",
    // Classes & Features
    Economy: "इकोनॉमी",
    Business: "बिजनेस",
    FirstClass: "फर्स्ट क्लास",
    light: "लाइट",
    flex: "फ्लेक्स",
    bag23kg: "1x 23kg बैग",
    bag2x23kg: "2x 23kg बैग",
    refundable: "वापसी योग्य",
    nonRefundable: "गैर वापसी योग्य",
    standardSeat: "मानक सीट",
    frontSeat: "सामने की सीट",
    // Reservation Page
    completeBooking: "अपनी बुकिंग पूरी करें",
    fillDetails: "अपनी सीट सुरक्षित करने के लिए नीचे विवरण भरें।",
    passengerDetails: "यात्री विवरण",
    flightSelection: "उड़ान चयन",
    chooseFlight: "उड़ान चुनें",
    travelClass: "यात्रा श्रेणी",
    selectSeat: "अपनी सीट चुनें",
    enhanceTrip: "अपनी यात्रा को बेहतर बनाएं",
    addHotel: "होटल जोड़ें",
    rentCar: "कार किराए पर लें",
    save20: "20% तक बचाएं",
    from30: "$30/दिन से",
    noSeats: "इस उड़ान के लिए कोई सीट उपलब्ध नहीं है।",
    selectFlightToView: "सीट मैप देखने के लिए कृपया एक उड़ान चुनें।",
    // Dynamic Cities
    city_New_York: "न्यूयॉर्क",
    city_London: "लंदन",
    city_Dubai: "दुबई",
    city_Riyadh: "रियाद",
    city_Paris: "पेरिस",
    city_Jeddah: "जेद्दा",
    city_Cairo: "काहिरा",
    city_Tokyo: "टोक्यो",
    city_Singapore: "सिंगापुर",
    city_Istanbul: "इस्तांबुल",
    // Seat Map
    front: "सामने",
    wing: "विंग",
    rear: "पीछे",
    exit: "निकास",
    available: "उपलब्ध",
    selected: "चयनित",
    booked: "बुक किया गया",
    // Passengers List
    passengersList: "यात्री सूची",
    noPassengers: "कोई यात्री नहीं मिला।",
    // Summary & Payment
    tripSummary: "यात्रा सारांश",
    flight: "उड़ान",
    route: "मार्ग",
    class: "श्रेणी",
    seat: "सीट",
    notSelected: "चयनित नहीं",
    totalPrice: "कुल कीमत",
    continuePayment: "भुगतान जारी रखें",
    processing: "प्रक्रिया जारी है...",
    securePayment: "सुरक्षित भुगतान",
    verifiedFlight: "सत्यापित उड़ान",
    support247: "24/7 सहायता",
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(
    localStorage.getItem("lang") || "en",
  );

  useEffect(() => {
    localStorage.setItem("lang", language);
    // Update document direction for Arabic
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    return translations[language][key] || key;
  };

  const switchLanguage = (lang) => {
    setLanguage(lang);
  };

  return (
    <LanguageContext.Provider value={{ language, switchLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
